image: node:18

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - npm run export
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - main
